Team 22 
Name : Praveen K 211AI028 
Chinta Tejdeep Reddy 211AI013

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

In [2]:
df = pd.read_csv(r"C:\Users\Praveen\Desktop\ASSIGNMENTSEM-III\DS\ACTUAL\Mobile_Recommendation_System-main\mainDataset.csv",encoding = "ISO-8859-1")

In [3]:
print(df.shape)

(961, 15)

In [4]:
print(df)

                                                Name  Rating Price Rs  RAM Gb  \
0             Realme Narzo 20 (Victory Blue, 128 GB)     4.5   11,499       4
1              Realme Narzo 20 (Victory Blue, 64 GB)     4.5   10,499       4
2             Realme Narzo 20 (Glory Sliver, 128 GB)     4.5   11,499       4
3              Realme Narzo 20 (Glory Sliver, 64 GB)     4.5   10,499       4
4                       POCO M2 (Pitch Black, 64 GB)     4.4   10,999       6
..                                               ...     ...      ...     ...
956                   Vivo U20 (Racing Black, 64 GB)     4.4   14,499       4
957  Samsung Galaxy S7 Edge (Silver Titanium, 32 GB)     4.4   41,900       4
958              Asus Zenfone 2 Laser (Black, 16 GB)     4.1   12,999       3
959                          Homtom H5 (Gold, 32 GB)     3.5    6,499       3
960                    LG G7 ThinQ (Platinum, 64 GB)     4.4   53,000       4

     ROM Gb  Expandable GB  Size Cm  Size Inch  R1 Cam MP  R2 Cam MP  \
0       128          256.0    16.56       6.52       48.0        8.0
1        64          256.0    16.56       6.52       48.0        8.0
2       128          256.0    16.56       6.52       48.0        8.0
3        64          256.0    16.56       6.52       48.0        8.0
4        64          512.0    16.59       6.53       13.0        8.0
..      ...            ...      ...        ...        ...        ...
956      64            NaN    16.59       6.53       16.0        NaN
957      32          200.0    13.97       5.50       12.0        NaN
958      16          128.0    13.97       5.50       13.0        NaN
959      32            NaN    13.97       5.50       16.0        NaN
960      64            2.0    15.49       6.10       16.0       16.0

    R3 Cam MP  R4 Cam MP  Battery Mah  \
0           2        NaN         6000
1           2        NaN         6000
2           2        NaN         6000
3           2        NaN         6000
4           5        2.0         5000
..        ...        ...          ...
956       NaN        NaN         5000
957       NaN        NaN         3600
958       NaN        NaN         3000
959       NaN        NaN         3300
960       NaN        NaN         3000

                                             Processor  \
0                         MediaTek Helio G85 Processor
1                         MediaTek Helio G85 Processor
2                         MediaTek Helio G85 Processor
3                         MediaTek Helio G85 Processor
4                         MediaTek Helio G80 Processor
..                                                 ...
956                  Qualcomm Snapdragon 665Â Processor
957                              Exynos 8890 Processor
958  Qualcomm Snapdragon 615 Octa Core 1.5GHz Proce...
959                                 Quadcore Processor
960                  Qualcomm Snapdragon 845 Processor

                                                 Image
0    https://rukminim1.flixcart.com/image/312/312/k...
1    https://rukminim1.flixcart.com/image/312/312/k...
2    https://rukminim1.flixcart.com/image/312/312/k...
3    https://rukminim1.flixcart.com/image/312/312/k...
4    https://rukminim1.flixcart.com/image/312/312/k...
..                                                 ...
956  https://img1a.flixcart.com/www/linchpin/fk-cp-...
957  https://img1a.flixcart.com/www/linchpin/fk-cp-...
958  https://img1a.flixcart.com/www/linchpin/fk-cp-...
959  https://img1a.flixcart.com/www/linchpin/fk-cp-...
960  https://img1a.flixcart.com/www/linchpin/fk-cp-...

[961 rows x 15 columns]

In [5]:
df.head()

,Name,Rating,Price Rs,RAM Gb,ROM Gb,Expandable GB,Size Cm,Size Inch,R1 Cam MP,R2 Cam MP,R3 Cam MP,R4 Cam MP,Battery Mah,Processor,Image
0,"Realme Narzo 20 (Victory Blue, 128 GB)",4.5,"11,499",4,128,256.0,16.56,6.52,48.0,8.0,2,NaN,6000,MediaTek Helio G85 Processor,https://rukminim1.flixcart.com/image/312/312/k...
1,"Realme Narzo 20 (Victory Blue, 64 GB)",4.5,"10,499",4,64,256.0,16.56,6.52,48.0,8.0,2,NaN,6000,MediaTek Helio G85 Processor,https://rukminim1.flixcart.com/image/312/312/k...
2,"Realme Narzo 20 (Glory Sliver, 128 GB)",4.5,"11,499",4,128,256.0,16.56,6.52,48.0,8.0,2,NaN,6000,MediaTek Helio G85 Processor,https://rukminim1.flixcart.com/image/312/312/k...
3,"Realme Narzo 20 (Glory Sliver, 64 GB)",4.5,"10,499",4,64,256.0,16.56,6.52,48.0,8.0,2,NaN,6000,MediaTek Helio G85 Processor,https://rukminim1.flixcart.com/image/312/312/k...
4,"POCO M2 (Pitch Black, 64 GB)",4.4,"10,999",6,64,512.0,16.59,6.53,13.0,8.0,5,2.0,5000,MediaTek Helio G80 Processor,https://rukminim1.flixcart.com/image/312/312/k...

In [6]:
df.describe()

,Rating,RAM Gb,ROM Gb,Expandable GB,Size Cm,Size Inch,R1 Cam MP,R2 Cam MP,R4 Cam MP,Battery Mah
count,936.000000,961.000000,961.000000,715.000000,961.000000,961.000000,961.000000,619.000000,205.000000,961.000000
mean,4.227137,4.500520,78.817898,298.641958,15.682352,6.173996,26.071176,6.707916,2.409756,4045.348595
std,0.368420,2.094201,65.408979,151.091947,1.162916,0.457630,20.892832,5.038164,1.114918,864.281378
min,2.300000,2.000000,16.000000,1.000000,12.700000,5.000000,5.000000,0.300000,2.000000,2200.000000
25%,4.200000,3.000000,32.000000,256.000000,15.210000,5.990000,13.000000,2.000000,2.000000,3300.000000
50%,4.300000,4.000000,64.000000,256.000000,16.000000,6.300000,13.000000,8.000000,2.000000,4000.000000
75%,4.400000,6.000000,128.000000,512.000000,16.510000,6.500000,48.000000,8.000000,2.000000,5000.000000
max,5.000000,12.000000,512.000000,512.000000,17.780000,7.000000,108.000000,48.000000,8.000000,6000.000000

In [7]:
df.isnull()

,Name,Rating,Price Rs,RAM Gb,ROM Gb,Expandable GB,Size Cm,Size Inch,R1 Cam MP,R2 Cam MP,R3 Cam MP,R4 Cam MP,Battery Mah,Processor,Image
0,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
956,False,False,False,False,False,True,False,False,False,True,True,True,False,False,False
957,False,False,False,False,False,False,False,False,False,True,True,True,False,False,False
958,False,False,False,False,False,False,False,False,False,True,True,True,False,False,False
959,False,False,False,False,False,True,False,False,False,True,True,True,False,False,False
960,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False

In [8]:
#This Gives the count of all the null values in each features
#df.isnull().sum()

In [9]:
#Here we are dropping all the records where the values are null
df2 = df.dropna()
print(df2)

                                                Name  Rating Price Rs  RAM Gb  \
4                       POCO M2 (Pitch Black, 64 GB)     4.4   10,999       6
9                        POCO M2 (Slate Blue, 64 GB)     4.4   10,999       6
10         Realme Narzo 20 Pro (White Knight, 64 GB)     4.7   14,999       6
11        Realme Narzo 20 Pro (White Knight, 128 GB)     4.5   16,999       8
17         Realme Narzo 20 Pro (Black Ninja, 128 GB)     4.5   16,999       8
..                                               ...     ...      ...     ...
610               OPPO Reno3 Pro (Sky White, 128 GB)     4.4   27,990       8
642          Samsung Galaxy M31 (Space Black, 64 GB)     4.3   18,105       6
833                    Lenovo Z6 Pro (Black, 128 GB)     3.8   26,999       8
868  Samsung Galaxy A71 (Prism Crush Silver, 128 GB)     4.4   33,990       8
943              Samsung Galaxy M30s (Black, 128 GB)     4.1   18,199       6

     ROM Gb  Expandable GB  Size Cm  Size Inch  R1 Cam MP  R2 Cam MP  \
4        64          512.0    16.59       6.53       13.0        8.0
9        64          512.0    16.59       6.53       13.0        8.0
10       64          256.0    16.51       6.50       48.0        8.0
11      128          256.0    16.51       6.50       48.0        8.0
17      128          256.0    16.51       6.50       48.0        8.0
..      ...            ...      ...        ...        ...        ...
610     128          256.0    16.26       6.40       64.0       13.0
642      64          512.0    16.26       6.40       64.0        8.0
833     128          512.0    16.23       6.39       48.0        2.0
868     128          512.0    17.02       6.70       64.0       12.0
943     128          512.0    16.26       6.40       48.0       48.0

    R3 Cam MP  R4 Cam MP  Battery Mah                             Processor  \
4           5        2.0         5000          MediaTek Helio G80 Processor
9           5        2.0         5000          MediaTek Helio G80 Processor
10          2        2.0         4500          MediaTek Helio G95 Processor
11          2        2.0         4500          MediaTek Helio G95 Processor
17          2        2.0         4500          MediaTek Helio G95 Processor
..        ...        ...          ...                                   ...
610         8        2.0         4025          MediaTek Helio P95 Processor
642         5        5.0         6000  Samsung Exynos 9 Octa 9611 Processor
833        16        8.0         4000             Qualcomm SDM855 Processor
868         5        5.0         4500             Qualcomm SM7150 Processor
943         8        5.0         6000                 Exynos 9611 Processor

                                                 Image
4    https://rukminim1.flixcart.com/image/312/312/k...
9    https://img1a.flixcart.com/www/linchpin/fk-cp-...
10   https://img1a.flixcart.com/www/linchpin/fk-cp-...
11   https://img1a.flixcart.com/www/linchpin/fk-cp-...
17   https://img1a.flixcart.com/www/linchpin/fk-cp-...
..                                                 ...
610  https://img1a.flixcart.com/www/linchpin/fk-cp-...
642  https://img1a.flixcart.com/www/linchpin/fk-cp-...
833  https://img1a.flixcart.com/www/linchpin/fk-cp-...
868  https://img1a.flixcart.com/www/linchpin/fk-cp-...
943  https://img1a.flixcart.com/www/linchpin/fk-cp-...

[155 rows x 15 columns]

In [10]:
#Now we are checking the mean,median,std after dropping the records
df2.describe()

,Rating,RAM Gb,ROM Gb,Expandable GB,Size Cm,Size Inch,R1 Cam MP,R2 Cam MP,R4 Cam MP,Battery Mah
count,155.000000,155.000000,155.000000,155.000000,155.000000,155.000000,155.000000,155.000000,155.000000,155.000000
mean,4.383871,6.316129,114.993548,373.277419,16.507613,6.498774,49.632258,8.819355,2.406452,4592.483871
std,0.108403,1.497855,47.784350,134.413325,0.278719,0.110138,14.517352,3.539152,1.085302,508.409914
min,3.800000,3.000000,32.000000,1.000000,16.000000,6.300000,12.000000,2.000000,2.000000,4000.000000
25%,4.300000,6.000000,64.000000,256.000000,16.260000,6.400000,48.000000,8.000000,2.000000,4035.000000
50%,4.400000,6.000000,128.000000,256.000000,16.510000,6.500000,48.000000,8.000000,2.000000,4500.000000
75%,4.400000,8.000000,128.000000,512.000000,16.590000,6.530000,64.000000,8.000000,2.000000,5000.000000
max,4.700000,8.000000,256.000000,512.000000,17.020000,6.700000,64.000000,48.000000,8.000000,6000.000000

In [11]:
df3 = df
print(df3)

                                                Name  Rating Price Rs  RAM Gb  \
0             Realme Narzo 20 (Victory Blue, 128 GB)     4.5   11,499       4
1              Realme Narzo 20 (Victory Blue, 64 GB)     4.5   10,499       4
2             Realme Narzo 20 (Glory Sliver, 128 GB)     4.5   11,499       4
3              Realme Narzo 20 (Glory Sliver, 64 GB)     4.5   10,499       4
4                       POCO M2 (Pitch Black, 64 GB)     4.4   10,999       6
..                                               ...     ...      ...     ...
956                   Vivo U20 (Racing Black, 64 GB)     4.4   14,499       4
957  Samsung Galaxy S7 Edge (Silver Titanium, 32 GB)     4.4   41,900       4
958              Asus Zenfone 2 Laser (Black, 16 GB)     4.1   12,999       3
959                          Homtom H5 (Gold, 32 GB)     3.5    6,499       3
960                    LG G7 ThinQ (Platinum, 64 GB)     4.4   53,000       4

     ROM Gb  Expandable GB  Size Cm  Size Inch  R1 Cam MP  R2 Cam MP  \
0       128          256.0    16.56       6.52       48.0        8.0
1        64          256.0    16.56       6.52       48.0        8.0
2       128          256.0    16.56       6.52       48.0        8.0
3        64          256.0    16.56       6.52       48.0        8.0
4        64          512.0    16.59       6.53       13.0        8.0
..      ...            ...      ...        ...        ...        ...
956      64            NaN    16.59       6.53       16.0        NaN
957      32          200.0    13.97       5.50       12.0        NaN
958      16          128.0    13.97       5.50       13.0        NaN
959      32            NaN    13.97       5.50       16.0        NaN
960      64            2.0    15.49       6.10       16.0       16.0

    R3 Cam MP  R4 Cam MP  Battery Mah  \
0           2        NaN         6000
1           2        NaN         6000
2           2        NaN         6000
3           2        NaN         6000
4           5        2.0         5000
..        ...        ...          ...
956       NaN        NaN         5000
957       NaN        NaN         3600
958       NaN        NaN         3000
959       NaN        NaN         3300
960       NaN        NaN         3000

                                             Processor  \
0                         MediaTek Helio G85 Processor
1                         MediaTek Helio G85 Processor
2                         MediaTek Helio G85 Processor
3                         MediaTek Helio G85 Processor
4                         MediaTek Helio G80 Processor
..                                                 ...
956                  Qualcomm Snapdragon 665Â Processor
957                              Exynos 8890 Processor
958  Qualcomm Snapdragon 615 Octa Core 1.5GHz Proce...
959                                 Quadcore Processor
960                  Qualcomm Snapdragon 845 Processor

                                                 Image
0    https://rukminim1.flixcart.com/image/312/312/k...
1    https://rukminim1.flixcart.com/image/312/312/k...
2    https://rukminim1.flixcart.com/image/312/312/k...
3    https://rukminim1.flixcart.com/image/312/312/k...
4    https://rukminim1.flixcart.com/image/312/312/k...
..                                                 ...
956  https://img1a.flixcart.com/www/linchpin/fk-cp-...
957  https://img1a.flixcart.com/www/linchpin/fk-cp-...
958  https://img1a.flixcart.com/www/linchpin/fk-cp-...
959  https://img1a.flixcart.com/www/linchpin/fk-cp-...
960  https://img1a.flixcart.com/www/linchpin/fk-cp-...

[961 rows x 15 columns]

In [12]:
#Filling the null values with the mean Imputation
df3['Rating'] = df3['Rating'].fillna(df3['Rating'].mean())
print(df3['Rating'].mean())
#df3['Price Rs'] = df['Price Rs'].fillna(df['Price Rs'].mean())
#print(df3['Price Rs'].mean())
df3['R2 Cam MP'] = df3['R2 Cam MP'].fillna(df3['R2 Cam MP'].mean())
print(df3['R2 Cam MP'].mean())
df3['R4 Cam MP'] = df3['R4 Cam MP'].fillna(df3['R4 Cam MP'].mean())
print(df3['R4 Cam MP'].mean())

4.227136752136752
6.707915993537965
2.4097560975609755

In [13]:
#Filling the null values with the median Imputation
df4 = df
df4['Rating'] = df4['Rating'].fillna(df4['Rating'].median())
print(df4['Rating'].median())
#df3['Price Rs'] = df['Price Rs'].fillna(df['Price Rs'].mean())
#print(df3['Price Rs'].mean())
df4['R2 Cam MP'] = df4['R2 Cam MP'].fillna(df4['R2 Cam MP'].median())
print(df4['R2 Cam MP'].median())
df4['R4 Cam MP'] = df4['R4 Cam MP'].fillna(df4['R4 Cam MP'].median())
print(df4['R4 Cam MP'].median())

4.3
6.707915993537964
2.4097560975609755

In [14]:
def combineFeatures(row):
        return str(row['Price Rs'])+" "+str(row['RAM Gb'])+" "+str(row['ROM Gb'])+" "+str(row['Size Inch'])+" "+str(row['R1 Cam MP'])+" "+str(row['Battery Mah'])

In [15]:
import eel
import json
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [17]:
#Implementing Cosine Similarity
data={
    "Name":['Realme'],
    "Rating":['4.6'],
    "Price Rs":['12000'],
    "RAM Gb":['8'],
    "ROM Gb":['32'],
    "Expandable GB":['256'],
    "Size Cm":['16'],
    "Size Inch":['6'],
    "R1 Cam MP":['48'],
    "R2 Cam MP":['8'],
    "R3 Cam MP":['2'],
    "R4 Cam MP":['2'],
    "Battery Mah":['5500'],
    "Processor":'MediaTek',
    "Image":' '
    }
#We have taken user preferences here for trial 
userDf=pd.DataFrame(data)


pf=pd.read_csv(r"C:\Users\Praveen\Desktop\ASSIGNMENTSEM-III\DS\ACTUAL\Mobile_Recommendation_System-main\mainDataset.csv",encoding= "ISO-8859-1")
#We are adding a new row vector which has the new row of data features at the beginning
pf=userDf.append(df,ignore_index = True)
#We here created a new columns which has a new value which creates a string with all the row values
pf["combinedFeatures"]=pf.apply(combineFeatures,axis=1)
cv=CountVectorizer()
#We here create matrix where each vector is count-vector.
countMatrix=cv.fit_transform(pf['combinedFeatures'])
#This creates a NxN matrix where each row is compared with all the rows and the cosine similar values
#are stored in that index
similar=cosine_similarity(countMatrix)
#We check the first row because it has the similarity of all all the phones in the databases with the user inputed phone.
similarPhones=list(enumerate(similar[0]))
#Sorting them according to the similarity value.
sortedSimilarPhones=sorted(similarPhones,key=lambda x:x[1], reverse=True)
for i in range(5):
    print(sortedSimilarPhones[i+1])
    print(pf.iloc[i])
#The index of the values of the phones in the database along with their probability found is printed

(186, 0.2886751345948129)
Name                              Realme
Rating                               4.6
Price Rs                           12000
RAM Gb                                 8
ROM Gb                                32
Expandable GB                        256
Size Cm                               16
Size Inch                              6
R1 Cam MP                             48
R2 Cam MP                              8
R3 Cam MP                              2
R4 Cam MP                              2
Battery Mah                         5500
Processor                       MediaTek
Image
combinedFeatures    12000 8 32 6 48 5500
Name: 0, dtype: object
(275, 0.2886751345948129)
Name                           Realme Narzo 20 (Victory Blue, 128 GB)
Rating                                                            4.5
Price Rs                                                       11,499
RAM Gb                                                              4
ROM Gb                                                            128
Expandable GB                                                   256.0
Size Cm                                                         16.56
Size Inch                                                        6.52
R1 Cam MP                                                        48.0
R2 Cam MP                                                         8.0
R3 Cam MP                                                           2
R4 Cam MP                                                    2.409756
Battery Mah                                                      6000
Processor                                MediaTek Helio G85 Processor
Image               https://rukminim1.flixcart.com/image/312/312/k...
combinedFeatures                          11,499 4 128 6.52 48.0 6000
Name: 1, dtype: object
(618, 0.2886751345948129)
Name                            Realme Narzo 20 (Victory Blue, 64 GB)
Rating                                                            4.5
Price Rs                                                       10,499
RAM Gb                                                              4
ROM Gb                                                             64
Expandable GB                                                   256.0
Size Cm                                                         16.56
Size Inch                                                        6.52
R1 Cam MP                                                        48.0
R2 Cam MP                                                         8.0
R3 Cam MP                                                           2
R4 Cam MP                                                    2.409756
Battery Mah                                                      6000
Processor                                MediaTek Helio G85 Processor
Image               https://rukminim1.flixcart.com/image/312/312/k...
combinedFeatures                           10,499 4 64 6.52 48.0 6000
Name: 2, dtype: object
(802, 0.2886751345948129)
Name                           Realme Narzo 20 (Glory Sliver, 128 GB)
Rating                                                            4.5
Price Rs                                                       11,499
RAM Gb                                                              4
ROM Gb                                                            128
Expandable GB                                                   256.0
Size Cm                                                         16.56
Size Inch                                                        6.52
R1 Cam MP                                                        48.0
R2 Cam MP                                                         8.0
R3 Cam MP                                                           2
R4 Cam MP                                                    2.409756
Battery Mah                                                      6000
Processor                                MediaTek Helio G85 Processor
Image               https://rukminim1.flixcart.com/image/312/312/k...
combinedFeatures                          11,499 4 128 6.52 48.0 6000
Name: 3, dtype: object
(828, 0.2886751345948129)
Name                            Realme Narzo 20 (Glory Sliver, 64 GB)
Rating                                                            4.5
Price Rs                                                       10,499
RAM Gb                                                              4
ROM Gb                                                             64
Expandable GB                                                   256.0
Size Cm                                                         16.56
Size Inch                                                        6.52
R1 Cam MP                                                        48.0
R2 Cam MP                                                         8.0
R3 Cam MP                                                           2
R4 Cam MP                                                    2.409756
Battery Mah                                                      6000
Processor                                MediaTek Helio G85 Processor
Image               https://rukminim1.flixcart.com/image/312/312/k...
combinedFeatures                           10,499 4 64 6.52 48.0 6000
Name: 4, dtype: object

C:\Users\Praveen\AppData\Local\Temp\ipykernel_5876\3853636511.py:25: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  pf=userDf.append(df,ignore_index = True)